webpackJsonp([1],{

/***/ 136:
/***/ (function(module, exports) {

function webpackEmptyAsyncContext(req) {
	// Here Promise.resolve().then() is used instead of new Promise() to prevent
	// uncatched exception popping up in devtools
	return Promise.resolve().then(function() {
		throw new Error("Cannot find module '" + req + "'.");
	});
}
webpackEmptyAsyncContext.keys = function() { return []; };
webpackEmptyAsyncContext.resolve = webpackEmptyAsyncContext;
module.exports = webpackEmptyAsyncContext;
webpackEmptyAsyncContext.id = 136;

/***/ }),

/***/ 137:
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__query_builder__ = __webpack_require__(324);
/* harmony namespace reexport (by used) */ __webpack_require__.d(__webpack_exports__, "a", function() { return __WEBPACK_IMPORTED_MODULE_0__query_builder__["a"]; });

//# sourceMappingURL=index.js.map

/***/ }),

/***/ 138:
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
Object.defineProperty(__webpack_exports__, "__esModule", { value: true });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "QueryBuilderModule", function() { return QueryBuilderModule; });
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__angular_core__ = __webpack_require__(20);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__angular_common__ = __webpack_require__(50);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_2__angular_forms__ = __webpack_require__(90);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_3__components__ = __webpack_require__(137);




var QueryBuilderModule = /** @class */ (function () {
    function QueryBuilderModule() {
    }
    QueryBuilderModule.decorators = [
        { type: __WEBPACK_IMPORTED_MODULE_0__angular_core__["NgModule"], args: [{
                    imports: [
                        __WEBPACK_IMPORTED_MODULE_1__angular_common__["CommonModule"],
                        __WEBPACK_IMPORTED_MODULE_2__angular_forms__["FormsModule"]
                    ],
                    declarations: [
                        __WEBPACK_IMPORTED_MODULE_3__components__["a" /* QueryBuilderComponent */]
                    ],
                    exports: [
                        __WEBPACK_IMPORTED_MODULE_3__components__["a" /* QueryBuilderComponent */]
                    ]
                },] },
    ];
    /** @nocollapse */
    QueryBuilderModule.ctorParameters = function () { return []; };
    return QueryBuilderModule;
}());

//# sourceMappingURL=query-builder.module.js.map

/***/ }),

/***/ 303:
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var platform_browser_1 = __webpack_require__(61);
var app_module_ngfactory_1 = __webpack_require__(321);
platform_browser_1.platformBrowser().bootstrapModuleFactory(app_module_ngfactory_1.AppModuleNgFactory);


/***/ }),

/***/ 321:
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
Object.defineProperty(exports, "__esModule", { value: true });
var i0 = __webpack_require__(20);
var i1 = __webpack_require__(322);
var i2 = __webpack_require__(88);
var i3 = __webpack_require__(330);
var i4 = __webpack_require__(50);
var i5 = __webpack_require__(61);
var i6 = __webpack_require__(90);
var i7 = __webpack_require__(138);
exports.AppModuleNgFactory = i0.ɵcmf(i1.AppModule, [i2.AppComponent], function (_l) {
    return i0.ɵmod([i0.ɵmpd(512, i0.ComponentFactoryResolver, i0.ɵCodegenComponentFactoryResolver, [[8, [i3.AppComponentNgFactory]], [3, i0.ComponentFactoryResolver], i0.NgModuleRef]),
        i0.ɵmpd(5120, i0.LOCALE_ID, i0.ɵm, [[3, i0.LOCALE_ID]]), i0.ɵmpd(4608, i4.NgLocalization, i4.NgLocaleLocalization, [i0.LOCALE_ID]), i0.ɵmpd(4608, i0.Compiler, i0.Compiler, []), i0.ɵmpd(5120, i0.APP_ID, i0.ɵf, []), i0.ɵmpd(5120, i0.IterableDiffers, i0.ɵk, []), i0.ɵmpd(5120, i0.KeyValueDiffers, i0.ɵl, []), i0.ɵmpd(4608, i5.DomSanitizer, i5.ɵe, [i4.DOCUMENT]),
        i0.ɵmpd(6144, i0.Sanitizer, null, [i5.DomSanitizer]), i0.ɵmpd(4608, i5.HAMMER_GESTURE_CONFIG, i5.HammerGestureConfig, []), i0.ɵmpd(5120, i5.EVENT_MANAGER_PLUGINS, function (p0_0, p1_0, p2_0, p2_1) {
            return [new i5.ɵDomEventsPlugin(p0_0), new i5.ɵKeyEventsPlugin(p1_0),
                new i5.ɵHammerGesturesPlugin(p2_0, p2_1)];
        }, [i4.DOCUMENT, i4.DOCUMENT, i4.DOCUMENT, i5.HAMMER_GESTURE_CONFIG]), i0.ɵmpd(4608, i5.EventManager, i5.EventManager, [i5.EVENT_MANAGER_PLUGINS, i0.NgZone]),
        i0.ɵmpd(135680, i5.ɵDomSharedStylesHost, i5.ɵDomSharedStylesHost, [i4.DOCUMENT]),
        i0.ɵmpd(4608, i5.ɵDomRendererFactory2, i5.ɵDomRendererFactory2, [i5.EventManager,
            i5.ɵDomSharedStylesHost]), i0.ɵmpd(6144, i0.RendererFactory2, null, [i5.ɵDomRendererFactory2]), i0.ɵmpd(6144, i5.ɵSharedStylesHost, null, [i5.ɵDomSharedStylesHost]), i0.ɵmpd(4608, i0.Testability, i0.Testability, [i0.NgZone]), i0.ɵmpd(4608, i5.Meta, i5.Meta, [i4.DOCUMENT]), i0.ɵmpd(4608, i5.Title, i5.Title, [i4.DOCUMENT]), i0.ɵmpd(4608, i6.ɵi, i6.ɵi, []),
        i0.ɵmpd(512, i4.CommonModule, i4.CommonModule, []), i0.ɵmpd(1024, i0.ErrorHandler, i5.ɵa, []), i0.ɵmpd(1024, i0.APP_INITIALIZER, function (p0_0, p0_1) {
            return [i5.ɵc(p0_0, p0_1)];
        }, [[2, i5.NgProbeToken], [2, i0.NgProbeToken]]), i0.ɵmpd(512, i0.ApplicationInitStatus, i0.ApplicationInitStatus, [[2, i0.APP_INITIALIZER]]), i0.ɵmpd(131584, i0.ɵe, i0.ɵe, [i0.NgZone, i0.ɵConsole, i0.Injector, i0.ErrorHandler, i0.ComponentFactoryResolver,
            i0.ApplicationInitStatus]), i0.ɵmpd(2048, i0.ApplicationRef, null, [i0.ɵe]), i0.ɵmpd(512, i0.ApplicationModule, i0.ApplicationModule, [i0.ApplicationRef]),
        i0.ɵmpd(512, i5.BrowserModule, i5.BrowserModule, [[3, i5.BrowserModule]]), i0.ɵmpd(512, i6.ɵba, i6.ɵba, []), i0.ɵmpd(512, i6.FormsModule, i6.FormsModule, []), i0.ɵmpd(512, i7.QueryBuilderModule, i7.QueryBuilderModule, []), i0.ɵmpd(512, i1.AppModule, i1.AppModule, [])]);
});



/***/ }),

/***/ 322:
/***/ (function(module, exports, __webpack_require__) {

"use strict";

var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
Object.defineProperty(exports, "__esModule", { value: true });
var core_1 = __webpack_require__(20);
var platform_browser_1 = __webpack_require__(61);
var app_component_1 = __webpack_require__(88);
var lib_1 = __webpack_require__(323);
var AppModule = /** @class */ (function () {
    function AppModule() {
    }
    AppModule = __decorate([
        core_1.NgModule({
            imports: [platform_browser_1.BrowserModule, lib_1.QueryBuilderModule],
            declarations: [app_component_1.AppComponent],
            bootstrap: [app_component_1.AppComponent]
        })
    ], AppModule);
    return AppModule;
}());
exports.AppModule = AppModule;


/***/ }),

/***/ 323:
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
Object.defineProperty(__webpack_exports__, "__esModule", { value: true });
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__components__ = __webpack_require__(137);
/* harmony reexport (binding) */ __webpack_require__.d(__webpack_exports__, "QueryBuilderComponent", function() { return __WEBPACK_IMPORTED_MODULE_0__components__["a"]; });
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__query_builder_module__ = __webpack_require__(138);
/* harmony reexport (binding) */ __webpack_require__.d(__webpack_exports__, "QueryBuilderModule", function() { return __WEBPACK_IMPORTED_MODULE_1__query_builder_module__["QueryBuilderModule"]; });


//# sourceMappingURL=index.js.map

/***/ }),

/***/ 324:
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__query_builder_component__ = __webpack_require__(89);
/* harmony namespace reexport (by used) */ __webpack_require__.d(__webpack_exports__, "a", function() { return __WEBPACK_IMPORTED_MODULE_0__query_builder_component__["QueryBuilderComponent"]; });

//# sourceMappingURL=index.js.map

/***/ }),

/***/ 330:
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
Object.defineProperty(exports, "__esModule", { value: true });
var i0 = __webpack_require__(20);
var i1 = __webpack_require__(331);
var i2 = __webpack_require__(89);
var i3 = __webpack_require__(50);
var i4 = __webpack_require__(88);
var styles_AppComponent = ['.margin30[_ngcontent-%COMP%] { margin: 30px; }',
    'textarea[_ngcontent-%COMP%] { width: 100%; height: 250px; }'];
exports.RenderType_AppComponent = i0.ɵcrt({ encapsulation: 0, styles: styles_AppComponent,
    data: {} });
function View_AppComponent_0(_l) {
    return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, null, null, 1, 'vr-query-builder', [['class', 'margin30']], null, null, null, i1.View_QueryBuilderComponent_0, i1.RenderType_QueryBuilderComponent)), i0.ɵdid(638976, null, 0, i2.QueryBuilderComponent, [], { data: [0, 'data'], config: [1, 'config'] }, null), (_l()(), i0.ɵted(null, ['\n  '])), (_l()(), i0.ɵeld(0, null, null, 5, 'div', [['class', 'margin30']], null, null, null, null, null)), (_l()(),
            i0.ɵted(null, ['\n      '])), (_l()(), i0.ɵeld(0, null, null, 2, 'textarea', [], null, null, null, null, null)), (_l()(), i0.ɵted(null, ['', ''])), i0.ɵpid(0, i3.JsonPipe, []), (_l()(), i0.ɵted(null, ['\n  ']))], function (_ck, _v) {
        var _co = _v.component;
        var currVal_0 = _co.query;
        var currVal_1 = _co.config;
        _ck(_v, 1, 0, currVal_0, currVal_1);
    }, function (_ck, _v) {
        var _co = _v.component;
        var currVal_2 = i0.ɵunv(_v, 6, 0, i0.ɵnov(_v, 7).transform(_co.query));
        _ck(_v, 6, 0, currVal_2);
    });
}
exports.View_AppComponent_0 = View_AppComponent_0;
function View_AppComponent_Host_0(_l) {
    return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, null, null, 1, 'my-app', [], null, null, null, View_AppComponent_0, exports.RenderType_AppComponent)),
        i0.ɵdid(49152, null, 0, i4.AppComponent, [], null, null)], null, null);
}
exports.View_AppComponent_Host_0 = View_AppComponent_Host_0;
exports.AppComponentNgFactory = i0.ɵccf('my-app', i4.AppComponent, View_AppComponent_Host_0, {}, {}, []);



/***/ }),

/***/ 331:
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
Object.defineProperty(exports, "__esModule", { value: true });
var i0 = __webpack_require__(20);
var i1 = __webpack_require__(90);
var i2 = __webpack_require__(50);
var i3 = __webpack_require__(89);
var styles_QueryBuilderComponent = ['[_nghost-%COMP%]{display:block}[_nghost-%COMP%]   .close-icon[_ngcontent-%COMP%]{font-style:normal;font-size:12px}[_nghost-%COMP%]   .switch-field[_ngcontent-%COMP%]{font-family:"Lucida Grande", Tahoma, Verdana, sans-serif;overflow:hidden}[_nghost-%COMP%]   .float-right[_ngcontent-%COMP%]{float:right}[_nghost-%COMP%]   .switch-title[_ngcontent-%COMP%]{margin-bottom:6px}[_nghost-%COMP%]   .form-control[_ngcontent-%COMP%]{display:inline-block;padding:4px 8px;color:#555;background-color:#fff;background-image:none;border:1px solid #ccc;border-radius:4px}[_nghost-%COMP%]   .switch-field[_ngcontent-%COMP%]   input[_ngcontent-%COMP%]{position:absolute;clip:rect(0, 0, 0, 0);height:1px;width:1px;border:0;overflow:hidden}[_nghost-%COMP%]   .switch-field[_ngcontent-%COMP%]   button[_ngcontent-%COMP%]{margin-left:8px;background-color:white}[_nghost-%COMP%]   .switch-field[_ngcontent-%COMP%]   label[_ngcontent-%COMP%]{background-color:#e4e4e4}[_nghost-%COMP%]   .switch-field[_ngcontent-%COMP%]   label[_ngcontent-%COMP%], [_nghost-%COMP%]   .switch-field[_ngcontent-%COMP%]   button[_ngcontent-%COMP%]{float:left;min-width:30px;color:rgba(0,0,0,0.6);font-size:14px;font-weight:normal;text-align:center;text-shadow:none;padding:4px 8px;border:1px solid rgba(0,0,0,0.2);-webkit-transition:all 0.1s ease-in-out;-moz-transition:all 0.1s ease-in-out;-ms-transition:all 0.1s ease-in-out;-o-transition:all 0.1s ease-in-out;transition:all 0.1s ease-in-out}[_nghost-%COMP%]   .switch-field[_ngcontent-%COMP%]   label[_ngcontent-%COMP%]:hover, [_nghost-%COMP%]   .switch-field[_ngcontent-%COMP%]   button[_ngcontent-%COMP%]:hover{cursor:pointer;background-color:#F0F0F0}[_nghost-%COMP%]   .switch-field[_ngcontent-%COMP%]   label.success[_ngcontent-%COMP%], [_nghost-%COMP%]   .switch-field[_ngcontent-%COMP%]   button.success[_ngcontent-%COMP%]{color:#75BE47}[_nghost-%COMP%]   .switch-field[_ngcontent-%COMP%]   label.danger[_ngcontent-%COMP%], [_nghost-%COMP%]   .switch-field[_ngcontent-%COMP%]   button.danger[_ngcontent-%COMP%]{color:#B3415D}[_nghost-%COMP%]   .switch-field[_ngcontent-%COMP%]   input[_ngcontent-%COMP%]:checked + label[_ngcontent-%COMP%]{border:1px solid #619ed7;background:white;color:#3176b3}[_nghost-%COMP%]   .invalid-ruleset[_ngcontent-%COMP%]{border:1px solid rgba(179,65,93,0.5) !important;background:rgba(179,65,93,0.1) !important}[_nghost-%COMP%]   .empty-warning[_ngcontent-%COMP%]{color:#8d252e;text-align:center}[_nghost-%COMP%]   .query-tree[_ngcontent-%COMP%]{list-style:none;margin:4px 0 2px}[_nghost-%COMP%]   .query-tree[_ngcontent-%COMP%]   .query-item[_ngcontent-%COMP%]{position:relative;padding:4px 6px;margin-top:4px;border:1px solid #CCCCCC;-webkit-transition:all 0.1s ease-in-out;-moz-transition:all 0.1s ease-in-out;-ms-transition:all 0.1s ease-in-out;-o-transition:all 0.1s ease-in-out;transition:all 0.1s ease-in-out}[_nghost-%COMP%]   .query-tree[_ngcontent-%COMP%]   .query-item.ruleset[_ngcontent-%COMP%]{background:rgba(204,204,204,0.2)}[_nghost-%COMP%]   .query-tree[_ngcontent-%COMP%]   .query-item.ruleset[_ngcontent-%COMP%]:hover{border:1px solid rgba(97,158,215,0.5);background:rgba(97,158,215,0.1)}[_nghost-%COMP%]   .query-tree[_ngcontent-%COMP%]   .query-item.rule[_ngcontent-%COMP%]{background:white}[_nghost-%COMP%]   .query-tree[_ngcontent-%COMP%]   .query-item[_ngcontent-%COMP%]::before{top:-5px;border-width:0 0 2px 2px}[_nghost-%COMP%]   .query-tree[_ngcontent-%COMP%]   .query-item[_ngcontent-%COMP%]::after{border-width:0 0 0 2px;top:50%}[_nghost-%COMP%]   .query-tree[_ngcontent-%COMP%]   .query-item[_ngcontent-%COMP%]::before, [_nghost-%COMP%]   .query-tree[_ngcontent-%COMP%]   .query-item[_ngcontent-%COMP%]::after{content:\'\';left:-12px;border-color:#CCC;border-style:solid;width:9px;height:calc(50% + 6px);position:absolute}[_nghost-%COMP%]   .query-tree[_ngcontent-%COMP%]   .query-item[_ngcontent-%COMP%]:last-child::after{content:none}'];
exports.RenderType_QueryBuilderComponent = i0.ɵcrt({ encapsulation: 0,
    styles: styles_QueryBuilderComponent, data: {} });
function View_QueryBuilderComponent_1(_l) {
    return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, null, null, 5, null, null, null, null, null, null, null)),
        (_l()(), i0.ɵted(null, ['\n            '])), (_l()(), i0.ɵeld(0, null, null, 2, 'button', [['class', 'danger']], null, [[null,
                'click']], function (_v, en, $event) {
            var ad = true;
            var _co = _v.component;
            if (('click' === en)) {
                var pd_0 = (_co.removeRuleSet(_co.data, _co.parentData) !== false);
                ad = (pd_0 && ad);
            }
            return ad;
        }, null, null)), (_l()(), i0.ɵeld(0, null, null, 1, 'i', [['class', 'close-icon']], null, null, null, null, null)), (_l()(), i0.ɵted(null, ['❌'])), (_l()(),
            i0.ɵted(null, ['\n        ']))], null, null);
}
function View_QueryBuilderComponent_5(_l) {
    return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, null, null, 3, 'option', [], null, null, null, null, null)), i0.ɵdid(147456, null, 0, i1.NgSelectOption, [i0.ElementRef, i0.Renderer2, [2, i1.SelectControlValueAccessor]], { ngValue: [0, 'ngValue'] }, null), i0.ɵdid(147456, null, 0, i1.ɵq, [i0.ElementRef, i0.Renderer2, [8, null]], { ngValue: [0, 'ngValue'] }, null),
        (_l()(), i0.ɵted(null, ['\n                    ', '\n                  ']))], function (_ck, _v) {
        var currVal_0 = _v.context.$implicit;
        _ck(_v, 1, 0, currVal_0);
        var currVal_1 = _v.context.$implicit;
        _ck(_v, 2, 0, currVal_1);
    }, function (_ck, _v) {
        var _co = _v.component;
        var currVal_2 = _co.config.fields[_v.context.$implicit].name;
        _ck(_v, 3, 0, currVal_2);
    });
}
function View_QueryBuilderComponent_6(_l) {
    return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, null, null, 3, 'option', [], null, null, null, null, null)), i0.ɵdid(147456, null, 0, i1.NgSelectOption, [i0.ElementRef, i0.Renderer2, [2, i1.SelectControlValueAccessor]], { ngValue: [0, 'ngValue'] }, null), i0.ɵdid(147456, null, 0, i1.ɵq, [i0.ElementRef, i0.Renderer2, [8, null]], { ngValue: [0, 'ngValue'] }, null),
        (_l()(), i0.ɵted(null, ['\n                    ', '\n                  ']))], function (_ck, _v) {
        var currVal_0 = _v.context.$implicit;
        _ck(_v, 1, 0, currVal_0);
        var currVal_1 = _v.context.$implicit;
        _ck(_v, 2, 0, currVal_1);
    }, function (_ck, _v) {
        var currVal_2 = _v.context.$implicit;
        _ck(_v, 3, 0, currVal_2);
    });
}
function View_QueryBuilderComponent_7(_l) {
    return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, null, null, 5, 'input', [['class',
                'form-control'], ['type', 'text']], [[2, 'ng-untouched', null], [2, 'ng-touched',
                null], [2, 'ng-pristine', null], [2, 'ng-dirty', null],
            [2, 'ng-valid', null], [2, 'ng-invalid', null], [2, 'ng-pending',
                null]], [[null, 'ngModelChange'], [null, 'input'],
            [null, 'blur'], [null, 'compositionstart'], [null, 'compositionend']], function (_v, en, $event) {
            var ad = true;
            if (('input' === en)) {
                var pd_0 = (i0.ɵnov(_v, 1)._handleInput($event.target.value) !== false);
                ad = (pd_0 && ad);
            }
            if (('blur' === en)) {
                var pd_1 = (i0.ɵnov(_v, 1).onTouched() !== false);
                ad = (pd_1 && ad);
            }
            if (('compositionstart' === en)) {
                var pd_2 = (i0.ɵnov(_v, 1)._compositionStart() !== false);
                ad = (pd_2 && ad);
            }
            if (('compositionend' === en)) {
                var pd_3 = (i0.ɵnov(_v, 1)._compositionEnd($event.target.value) !== false);
                ad = (pd_3 && ad);
            }
            if (('ngModelChange' === en)) {
                var pd_4 = ((_v.parent.parent.parent.context.$implicit.value = $event) !== false);
                ad = (pd_4 && ad);
            }
            return ad;
        }, null, null)), i0.ɵdid(16384, null, 0, i1.DefaultValueAccessor, [i0.Renderer2, i0.ElementRef, [2, i1.COMPOSITION_BUFFER_MODE]], null, null),
        i0.ɵprd(1024, null, i1.NG_VALUE_ACCESSOR, function (p0_0) {
            return [p0_0];
        }, [i1.DefaultValueAccessor]), i0.ɵdid(671744, null, 0, i1.NgModel, [[8, null],
            [8, null], [8, null], [2, i1.NG_VALUE_ACCESSOR]], { model: [0,
                'model'] }, { update: 'ngModelChange' }), i0.ɵprd(2048, null, i1.NgControl, null, [i1.NgModel]), i0.ɵdid(16384, null, 0, i1.NgControlStatus, [i1.NgControl], null, null)], function (_ck, _v) {
        var currVal_7 = _v.parent.parent.parent.context.$implicit.value;
        _ck(_v, 3, 0, currVal_7);
    }, function (_ck, _v) {
        var currVal_0 = i0.ɵnov(_v, 5).ngClassUntouched;
        var currVal_1 = i0.ɵnov(_v, 5).ngClassTouched;
        var currVal_2 = i0.ɵnov(_v, 5).ngClassPristine;
        var currVal_3 = i0.ɵnov(_v, 5).ngClassDirty;
        var currVal_4 = i0.ɵnov(_v, 5).ngClassValid;
        var currVal_5 = i0.ɵnov(_v, 5).ngClassInvalid;
        var currVal_6 = i0.ɵnov(_v, 5).ngClassPending;
        _ck(_v, 0, 0, currVal_0, currVal_1, currVal_2, currVal_3, currVal_4, currVal_5, currVal_6);
    });
}
function View_QueryBuilderComponent_8(_l) {
    return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, null, null, 5, 'input', [['class',
                'form-control'], ['type', 'date']], [[2, 'ng-untouched', null], [2, 'ng-touched',
                null], [2, 'ng-pristine', null], [2, 'ng-dirty', null],
            [2, 'ng-valid', null], [2, 'ng-invalid', null], [2, 'ng-pending',
                null]], [[null, 'ngModelChange'], [null, 'input'],
            [null, 'blur'], [null, 'compositionstart'], [null, 'compositionend']], function (_v, en, $event) {
            var ad = true;
            if (('input' === en)) {
                var pd_0 = (i0.ɵnov(_v, 1)._handleInput($event.target.value) !== false);
                ad = (pd_0 && ad);
            }
            if (('blur' === en)) {
                var pd_1 = (i0.ɵnov(_v, 1).onTouched() !== false);
                ad = (pd_1 && ad);
            }
            if (('compositionstart' === en)) {
                var pd_2 = (i0.ɵnov(_v, 1)._compositionStart() !== false);
                ad = (pd_2 && ad);
            }
            if (('compositionend' === en)) {
                var pd_3 = (i0.ɵnov(_v, 1)._compositionEnd($event.target.value) !== false);
                ad = (pd_3 && ad);
            }
            if (('ngModelChange' === en)) {
                var pd_4 = ((_v.parent.parent.parent.context.$implicit.value = $event) !== false);
                ad = (pd_4 && ad);
            }
            return ad;
        }, null, null)), i0.ɵdid(16384, null, 0, i1.DefaultValueAccessor, [i0.Renderer2, i0.ElementRef, [2, i1.COMPOSITION_BUFFER_MODE]], null, null),
        i0.ɵprd(1024, null, i1.NG_VALUE_ACCESSOR, function (p0_0) {
            return [p0_0];
        }, [i1.DefaultValueAccessor]), i0.ɵdid(671744, null, 0, i1.NgModel, [[8, null],
            [8, null], [8, null], [2, i1.NG_VALUE_ACCESSOR]], { model: [0,
                'model'] }, { update: 'ngModelChange' }), i0.ɵprd(2048, null, i1.NgControl, null, [i1.NgModel]), i0.ɵdid(16384, null, 0, i1.NgControlStatus, [i1.NgControl], null, null)], function (_ck, _v) {
        var currVal_7 = _v.parent.parent.parent.context.$implicit.value;
        _ck(_v, 3, 0, currVal_7);
    }, function (_ck, _v) {
        var currVal_0 = i0.ɵnov(_v, 5).ngClassUntouched;
        var currVal_1 = i0.ɵnov(_v, 5).ngClassTouched;
        var currVal_2 = i0.ɵnov(_v, 5).ngClassPristine;
        var currVal_3 = i0.ɵnov(_v, 5).ngClassDirty;
        var currVal_4 = i0.ɵnov(_v, 5).ngClassValid;
        var currVal_5 = i0.ɵnov(_v, 5).ngClassInvalid;
        var currVal_6 = i0.ɵnov(_v, 5).ngClassPending;
        _ck(_v, 0, 0, currVal_0, currVal_1, currVal_2, currVal_3, currVal_4, currVal_5, currVal_6);
    });
}
function View_QueryBuilderComponent_9(_l) {
    return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, null, null, 6, 'input', [['class',
                'form-control'], ['type', 'number']], [[2, 'ng-untouched', null], [2, 'ng-touched',
                null], [2, 'ng-pristine', null], [2, 'ng-dirty', null],
            [2, 'ng-valid', null], [2, 'ng-invalid', null], [2, 'ng-pending',
                null]], [[null, 'ngModelChange'], [null, 'input'],
            [null, 'blur'], [null, 'compositionstart'], [null, 'compositionend'],
            [null, 'change']], function (_v, en, $event) {
            var ad = true;
            if (('input' === en)) {
                var pd_0 = (i0.ɵnov(_v, 1)._handleInput($event.target.value) !== false);
                ad = (pd_0 && ad);
            }
            if (('blur' === en)) {
                var pd_1 = (i0.ɵnov(_v, 1).onTouched() !== false);
                ad = (pd_1 && ad);
            }
            if (('compositionstart' === en)) {
                var pd_2 = (i0.ɵnov(_v, 1)._compositionStart() !== false);
                ad = (pd_2 && ad);
            }
            if (('compositionend' === en)) {
                var pd_3 = (i0.ɵnov(_v, 1)._compositionEnd($event.target.value) !== false);
                ad = (pd_3 && ad);
            }
            if (('change' === en)) {
                var pd_4 = (i0.ɵnov(_v, 2).onChange($event.target.value) !== false);
                ad = (pd_4 && ad);
            }
            if (('input' === en)) {
                var pd_5 = (i0.ɵnov(_v, 2).onChange($event.target.value) !== false);
                ad = (pd_5 && ad);
            }
            if (('blur' === en)) {
                var pd_6 = (i0.ɵnov(_v, 2).onTouched() !== false);
                ad = (pd_6 && ad);
            }
            if (('ngModelChange' === en)) {
                var pd_7 = ((_v.parent.parent.parent.context.$implicit.value = $event) !== false);
                ad = (pd_7 && ad);
            }
            return ad;
        }, null, null)), i0.ɵdid(16384, null, 0, i1.DefaultValueAccessor, [i0.Renderer2, i0.ElementRef, [2, i1.COMPOSITION_BUFFER_MODE]], null, null),
        i0.ɵdid(16384, null, 0, i1.ɵbc, [i0.Renderer2, i0.ElementRef], null, null), i0.ɵprd(1024, null, i1.NG_VALUE_ACCESSOR, function (p0_0, p1_0) {
            return [p0_0, p1_0];
        }, [i1.DefaultValueAccessor, i1.ɵbc]), i0.ɵdid(671744, null, 0, i1.NgModel, [[8, null], [8, null], [8, null], [2, i1.NG_VALUE_ACCESSOR]], { model: [0, 'model'] }, { update: 'ngModelChange' }), i0.ɵprd(2048, null, i1.NgControl, null, [i1.NgModel]), i0.ɵdid(16384, null, 0, i1.NgControlStatus, [i1.NgControl], null, null)], function (_ck, _v) {
        var currVal_7 = _v.parent.parent.parent.context.$implicit.value;
        _ck(_v, 4, 0, currVal_7);
    }, function (_ck, _v) {
        var currVal_0 = i0.ɵnov(_v, 6).ngClassUntouched;
        var currVal_1 = i0.ɵnov(_v, 6).ngClassTouched;
        var currVal_2 = i0.ɵnov(_v, 6).ngClassPristine;
        var currVal_3 = i0.ɵnov(_v, 6).ngClassDirty;
        var currVal_4 = i0.ɵnov(_v, 6).ngClassValid;
        var currVal_5 = i0.ɵnov(_v, 6).ngClassInvalid;
        var currVal_6 = i0.ɵnov(_v, 6).ngClassPending;
        _ck(_v, 0, 0, currVal_0, currVal_1, currVal_2, currVal_3, currVal_4, currVal_5, currVal_6);
    });
}
function View_QueryBuilderComponent_11(_l) {
    return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, null, null, 3, 'option', [], null, null, null, null, null)), i0.ɵdid(147456, null, 0, i1.NgSelectOption, [i0.ElementRef, i0.Renderer2, [2, i1.SelectControlValueAccessor]], { ngValue: [0, 'ngValue'] }, null), i0.ɵdid(147456, null, 0, i1.ɵq, [i0.ElementRef, i0.Renderer2, [8, null]], { ngValue: [0, 'ngValue'] }, null),
        (_l()(), i0.ɵted(null, ['\n                      ', '\n                    ']))], function (_ck, _v) {
        var currVal_0 = _v.context.$implicit.value;
        _ck(_v, 1, 0, currVal_0);
        var currVal_1 = _v.context.$implicit.value;
        _ck(_v, 2, 0, currVal_1);
    }, function (_ck, _v) {
        var currVal_2 = _v.context.$implicit.name;
        _ck(_v, 3, 0, currVal_2);
    });
}
function View_QueryBuilderComponent_10(_l) {
    return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, null, null, 9, 'select', [['class',
                'form-control']], [[2, 'ng-untouched', null], [2, 'ng-touched', null],
            [2, 'ng-pristine', null], [2, 'ng-dirty', null], [2, 'ng-valid', null],
            [2, 'ng-invalid', null], [2, 'ng-pending', null]], [[null,
                'ngModelChange'], [null, 'change'], [null, 'blur']], function (_v, en, $event) {
            var ad = true;
            if (('change' === en)) {
                var pd_0 = (i0.ɵnov(_v, 1).onChange($event.target.value) !== false);
                ad = (pd_0 && ad);
            }
            if (('blur' === en)) {
                var pd_1 = (i0.ɵnov(_v, 1).onTouched() !== false);
                ad = (pd_1 && ad);
            }
            if (('ngModelChange' === en)) {
                var pd_2 = ((_v.parent.parent.parent.context.$implicit.value = $event) !== false);
                ad = (pd_2 && ad);
            }
            return ad;
        }, null, null)), i0.ɵdid(16384, null, 0, i1.SelectControlValueAccessor, [i0.Renderer2, i0.ElementRef], null, null), i0.ɵprd(1024, null, i1.NG_VALUE_ACCESSOR, function (p0_0) {
            return [p0_0];
        }, [i1.SelectControlValueAccessor]), i0.ɵdid(671744, null, 0, i1.NgModel, [[8, null], [8, null], [8, null], [2, i1.NG_VALUE_ACCESSOR]], { model: [0, 'model'] }, { update: 'ngModelChange' }), i0.ɵprd(2048, null, i1.NgControl, null, [i1.NgModel]), i0.ɵdid(16384, null, 0, i1.NgControlStatus, [i1.NgControl], null, null), (_l()(), i0.ɵted(null, ['\n                    '])),
        (_l()(), i0.ɵand(16777216, null, null, 1, null, View_QueryBuilderComponent_11)),
        i0.ɵdid(802816, null, 0, i2.NgForOf, [i0.ViewContainerRef, i0.TemplateRef,
            i0.IterableDiffers], { ngForOf: [0, 'ngForOf'] }, null), (_l()(), i0.ɵted(null, ['\n                  ']))], function (_ck, _v) {
        var _co = _v.component;
        var currVal_7 = _v.parent.parent.parent.context.$implicit.value;
        _ck(_v, 3, 0, currVal_7);
        var currVal_8 = _co.getOptions(_v.parent.parent.parent.context.$implicit.field);
        _ck(_v, 8, 0, currVal_8);
    }, function (_ck, _v) {
        var currVal_0 = i0.ɵnov(_v, 5).ngClassUntouched;
        var currVal_1 = i0.ɵnov(_v, 5).ngClassTouched;
        var currVal_2 = i0.ɵnov(_v, 5).ngClassPristine;
        var currVal_3 = i0.ɵnov(_v, 5).ngClassDirty;
        var currVal_4 = i0.ɵnov(_v, 5).ngClassValid;
        var currVal_5 = i0.ɵnov(_v, 5).ngClassInvalid;
        var currVal_6 = i0.ɵnov(_v, 5).ngClassPending;
        _ck(_v, 0, 0, currVal_0, currVal_1, currVal_2, currVal_3, currVal_4, currVal_5, currVal_6);
    });
}
function View_QueryBuilderComponent_13(_l) {
    return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, null, null, 3, 'option', [], null, null, null, null, null)), i0.ɵdid(147456, null, 0, i1.NgSelectOption, [i0.ElementRef, i0.Renderer2, [8, null]], { ngValue: [0, 'ngValue'] }, null), i0.ɵdid(147456, null, 0, i1.ɵq, [i0.ElementRef, i0.Renderer2, [2, i1.SelectMultipleControlValueAccessor]], { ngValue: [0,
                'ngValue'] }, null), (_l()(), i0.ɵted(null, ['\n                        ',
            '\n                      ']))], function (_ck, _v) {
        var currVal_0 = _v.context.$implicit.value;
        _ck(_v, 1, 0, currVal_0);
        var currVal_1 = _v.context.$implicit.value;
        _ck(_v, 2, 0, currVal_1);
    }, function (_ck, _v) {
        var currVal_2 = _v.context.$implicit.name;
        _ck(_v, 3, 0, currVal_2);
    });
}
function View_QueryBuilderComponent_12(_l) {
    return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, null, null, 14, null, null, null, null, null, null, null)),
        (_l()(), i0.ɵted(null, ['\n                    '])), (_l()(), i0.ɵeld(0, null, null, 0, 'div', [['style', 'margin-bottom: 8px']], null, null, null, null, null)), (_l()(), i0.ɵted(null, ['\n                    '])), (_l()(), i0.ɵeld(0, null, null, 9, 'select', [['class', 'form-control'], ['multiple', ''], ['style', 'min-width: 200px']], [[2, 'ng-untouched', null], [2, 'ng-touched', null], [2, 'ng-pristine',
                null], [2, 'ng-dirty', null], [2, 'ng-valid', null],
            [2, 'ng-invalid', null], [2, 'ng-pending', null]], [[null,
                'ngModelChange'], [null, 'change'], [null, 'blur']], function (_v, en, $event) {
            var ad = true;
            if (('change' === en)) {
                var pd_0 = (i0.ɵnov(_v, 5).onChange($event.target) !== false);
                ad = (pd_0 && ad);
            }
            if (('blur' === en)) {
                var pd_1 = (i0.ɵnov(_v, 5).onTouched() !== false);
                ad = (pd_1 && ad);
            }
            if (('ngModelChange' === en)) {
                var pd_2 = ((_v.parent.parent.parent.context.$implicit.value = $event) !== false);
                ad = (pd_2 && ad);
            }
            return ad;
        }, null, null)), i0.ɵdid(16384, null, 0, i1.SelectMultipleControlValueAccessor, [i0.Renderer2, i0.ElementRef], null, null), i0.ɵprd(1024, null, i1.NG_VALUE_ACCESSOR, function (p0_0) {
            return [p0_0];
        }, [i1.SelectMultipleControlValueAccessor]), i0.ɵdid(671744, null, 0, i1.NgModel, [[8, null], [8, null], [8, null], [2, i1.NG_VALUE_ACCESSOR]], { model: [0, 'model'] }, { update: 'ngModelChange' }), i0.ɵprd(2048, null, i1.NgControl, null, [i1.NgModel]), i0.ɵdid(16384, null, 0, i1.NgControlStatus, [i1.NgControl], null, null), (_l()(), i0.ɵted(null, ['\n                      '])), (_l()(), i0.ɵand(16777216, null, null, 1, null, View_QueryBuilderComponent_13)), i0.ɵdid(802816, null, 0, i2.NgForOf, [i0.ViewContainerRef, i0.TemplateRef, i0.IterableDiffers], { ngForOf: [0,
                'ngForOf'] }, null), (_l()(), i0.ɵted(null, ['\n                    '])),
        (_l()(), i0.ɵted(null, ['\n                  ']))], function (_ck, _v) {
        var _co = _v.component;
        var currVal_7 = _v.parent.parent.parent.context.$implicit.value;
        _ck(_v, 7, 0, currVal_7);
        var currVal_8 = _co.getOptions(_v.parent.parent.parent.context.$implicit.field);
        _ck(_v, 12, 0, currVal_8);
    }, function (_ck, _v) {
        var currVal_0 = i0.ɵnov(_v, 9).ngClassUntouched;
        var currVal_1 = i0.ɵnov(_v, 9).ngClassTouched;
        var currVal_2 = i0.ɵnov(_v, 9).ngClassPristine;
        var currVal_3 = i0.ɵnov(_v, 9).ngClassDirty;
        var currVal_4 = i0.ɵnov(_v, 9).ngClassValid;
        var currVal_5 = i0.ɵnov(_v, 9).ngClassInvalid;
        var currVal_6 = i0.ɵnov(_v, 9).ngClassPending;
        _ck(_v, 4, 0, currVal_0, currVal_1, currVal_2, currVal_3, currVal_4, currVal_5, currVal_6);
    });
}
function View_QueryBuilderComponent_14(_l) {
    return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, null, null, 5, 'input', [['class',
                'form-control'], ['type', 'checkbox']], [[2, 'ng-untouched', null], [2, 'ng-touched',
                null], [2, 'ng-pristine', null], [2, 'ng-dirty', null],
            [2, 'ng-valid', null], [2, 'ng-invalid', null], [2, 'ng-pending',
                null]], [[null, 'ngModelChange'], [null, 'change'],
            [null, 'blur']], function (_v, en, $event) {
            var ad = true;
            if (('change' === en)) {
                var pd_0 = (i0.ɵnov(_v, 1).onChange($event.target.checked) !== false);
                ad = (pd_0 && ad);
            }
            if (('blur' === en)) {
                var pd_1 = (i0.ɵnov(_v, 1).onTouched() !== false);
                ad = (pd_1 && ad);
            }
            if (('ngModelChange' === en)) {
                var pd_2 = ((_v.parent.parent.parent.context.$implicit.value = $event) !== false);
                ad = (pd_2 && ad);
            }
            return ad;
        }, null, null)), i0.ɵdid(16384, null, 0, i1.CheckboxControlValueAccessor, [i0.Renderer2, i0.ElementRef], null, null), i0.ɵprd(1024, null, i1.NG_VALUE_ACCESSOR, function (p0_0) {
            return [p0_0];
        }, [i1.CheckboxControlValueAccessor]), i0.ɵdid(671744, null, 0, i1.NgModel, [[8, null], [8, null], [8, null], [2, i1.NG_VALUE_ACCESSOR]], { model: [0, 'model'] }, { update: 'ngModelChange' }), i0.ɵprd(2048, null, i1.NgControl, null, [i1.NgModel]), i0.ɵdid(16384, null, 0, i1.NgControlStatus, [i1.NgControl], null, null)], function (_ck, _v) {
        var currVal_7 = _v.parent.parent.parent.context.$implicit.value;
        _ck(_v, 3, 0, currVal_7);
    }, function (_ck, _v) {
        var currVal_0 = i0.ɵnov(_v, 5).ngClassUntouched;
        var currVal_1 = i0.ɵnov(_v, 5).ngClassTouched;
        var currVal_2 = i0.ɵnov(_v, 5).ngClassPristine;
        var currVal_3 = i0.ɵnov(_v, 5).ngClassDirty;
        var currVal_4 = i0.ɵnov(_v, 5).ngClassValid;
        var currVal_5 = i0.ɵnov(_v, 5).ngClassInvalid;
        var currVal_6 = i0.ɵnov(_v, 5).ngClassPending;
        _ck(_v, 0, 0, currVal_0, currVal_1, currVal_2, currVal_3, currVal_4, currVal_5, currVal_6);
    });
}
function View_QueryBuilderComponent_4(_l) {
    return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, null, null, 52, null, null, null, null, null, null, null)),
        (_l()(), i0.ɵted(null, ['\n                '])), (_l()(), i0.ɵeld(0, null, null, 5, 'div', [['class', 'switch-field float-right']], null, null, null, null, null)), (_l()(), i0.ɵted(null, ['\n                  '])), (_l()(), i0.ɵeld(0, null, null, 2, 'button', [['class', 'danger']], null, [[null, 'click']], function (_v, en, $event) {
            var ad = true;
            var _co = _v.component;
            if (('click' === en)) {
                var pd_0 = (_co.removeRule(_v.parent.parent.context.$implicit, _co.data) !== false);
                ad = (pd_0 && ad);
            }
            return ad;
        }, null, null)), (_l()(), i0.ɵeld(0, null, null, 1, 'i', [['class', 'close-icon']], null, null, null, null, null)), (_l()(), i0.ɵted(null, ['❌'])), (_l()(),
            i0.ɵted(null, ['\n                '])), (_l()(), i0.ɵted(null, ['\n\n                '])), (_l()(), i0.ɵeld(0, null, null, 9, 'select', [['class', 'form-control']], [[2, 'ng-untouched', null],
            [2, 'ng-touched', null], [2, 'ng-pristine', null], [2, 'ng-dirty',
                null], [2, 'ng-valid', null], [2, 'ng-invalid', null],
            [2, 'ng-pending', null]], [[null, 'ngModelChange'], [null,
                'change'], [null, 'blur']], function (_v, en, $event) {
            var ad = true;
            var _co = _v.component;
            if (('change' === en)) {
                var pd_0 = (i0.ɵnov(_v, 10).onChange($event.target.value) !== false);
                ad = (pd_0 && ad);
            }
            if (('blur' === en)) {
                var pd_1 = (i0.ɵnov(_v, 10).onTouched() !== false);
                ad = (pd_1 && ad);
            }
            if (('ngModelChange' === en)) {
                var pd_2 = ((_v.parent.parent.context.$implicit.field = $event) !== false);
                ad = (pd_2 && ad);
            }
            if (('change' === en)) {
                var pd_3 = (_co.onFieldChange(_v.parent.parent.context.$implicit) !== false);
                ad = (pd_3 && ad);
            }
            return ad;
        }, null, null)), i0.ɵdid(16384, null, 0, i1.SelectControlValueAccessor, [i0.Renderer2, i0.ElementRef], null, null), i0.ɵprd(1024, null, i1.NG_VALUE_ACCESSOR, function (p0_0) {
            return [p0_0];
        }, [i1.SelectControlValueAccessor]), i0.ɵdid(671744, null, 0, i1.NgModel, [[8, null], [8, null], [8, null], [2, i1.NG_VALUE_ACCESSOR]], { model: [0, 'model'] }, { update: 'ngModelChange' }), i0.ɵprd(2048, null, i1.NgControl, null, [i1.NgModel]), i0.ɵdid(16384, null, 0, i1.NgControlStatus, [i1.NgControl], null, null), (_l()(), i0.ɵted(null, ['\n                  '])), (_l()(), i0.ɵand(16777216, null, null, 1, null, View_QueryBuilderComponent_5)), i0.ɵdid(802816, null, 0, i2.NgForOf, [i0.ViewContainerRef, i0.TemplateRef, i0.IterableDiffers], { ngForOf: [0,
                'ngForOf'] }, null), (_l()(), i0.ɵted(null, ['\n                '])),
        (_l()(), i0.ɵted(null, ['\n                '])), (_l()(), i0.ɵeld(0, null, null, 9, 'select', [['class', 'form-control']], [[2, 'ng-untouched', null],
            [2, 'ng-touched', null], [2, 'ng-pristine', null], [2, 'ng-dirty',
                null], [2, 'ng-valid', null], [2, 'ng-invalid', null],
            [2, 'ng-pending', null]], [[null, 'ngModelChange'], [null,
                'change'], [null, 'blur']], function (_v, en, $event) {
            var ad = true;
            if (('change' === en)) {
                var pd_0 = (i0.ɵnov(_v, 21).onChange($event.target.value) !== false);
                ad = (pd_0 && ad);
            }
            if (('blur' === en)) {
                var pd_1 = (i0.ɵnov(_v, 21).onTouched() !== false);
                ad = (pd_1 && ad);
            }
            if (('ngModelChange' === en)) {
                var pd_2 = ((_v.parent.parent.context.$implicit.operator = $event) !== false);
                ad = (pd_2 && ad);
            }
            return ad;
        }, null, null)), i0.ɵdid(16384, null, 0, i1.SelectControlValueAccessor, [i0.Renderer2, i0.ElementRef], null, null), i0.ɵprd(1024, null, i1.NG_VALUE_ACCESSOR, function (p0_0) {
            return [p0_0];
        }, [i1.SelectControlValueAccessor]), i0.ɵdid(671744, null, 0, i1.NgModel, [[8, null], [8, null], [8, null], [2, i1.NG_VALUE_ACCESSOR]], { model: [0, 'model'] }, { update: 'ngModelChange' }), i0.ɵprd(2048, null, i1.NgControl, null, [i1.NgModel]), i0.ɵdid(16384, null, 0, i1.NgControlStatus, [i1.NgControl], null, null), (_l()(), i0.ɵted(null, ['\n                  '])), (_l()(), i0.ɵand(16777216, null, null, 1, null, View_QueryBuilderComponent_6)), i0.ɵdid(802816, null, 0, i2.NgForOf, [i0.ViewContainerRef, i0.TemplateRef, i0.IterableDiffers], { ngForOf: [0,
                'ngForOf'] }, null), (_l()(), i0.ɵted(null, ['\n                '])),
        (_l()(), i0.ɵted(null, ['\n                '])), (_l()(), i0.ɵeld(0, null, null, 20, null, null, null, null, null, null, null)), i0.ɵdid(16384, null, 0, i2.NgSwitch, [], { ngSwitch: [0, 'ngSwitch'] }, null), (_l()(),
            i0.ɵted(null, ['\n                  '])), (_l()(), i0.ɵand(16777216, null, null, 1, null, View_QueryBuilderComponent_7)),
        i0.ɵdid(278528, null, 0, i2.NgSwitchCase, [i0.ViewContainerRef, i0.TemplateRef,
            i2.NgSwitch], { ngSwitchCase: [0, 'ngSwitchCase'] }, null), (_l()(), i0.ɵted(null, ['\n                  '])), (_l()(), i0.ɵand(16777216, null, null, 1, null, View_QueryBuilderComponent_8)), i0.ɵdid(278528, null, 0, i2.NgSwitchCase, [i0.ViewContainerRef, i0.TemplateRef, i2.NgSwitch], { ngSwitchCase: [0,
                'ngSwitchCase'] }, null), (_l()(), i0.ɵted(null, ['\n                  '])),
        (_l()(), i0.ɵand(16777216, null, null, 1, null, View_QueryBuilderComponent_9)),
        i0.ɵdid(278528, null, 0, i2.NgSwitchCase, [i0.ViewContainerRef, i0.TemplateRef,
            i2.NgSwitch], { ngSwitchCase: [0, 'ngSwitchCase'] }, null), (_l()(), i0.ɵted(null, ['\n                  '])), (_l()(), i0.ɵand(16777216, null, null, 1, null, View_QueryBuilderComponent_10)), i0.ɵdid(278528, null, 0, i2.NgSwitchCase, [i0.ViewContainerRef, i0.TemplateRef, i2.NgSwitch], { ngSwitchCase: [0,
                'ngSwitchCase'] }, null), (_l()(), i0.ɵted(null, ['\n                  '])),
        (_l()(), i0.ɵand(16777216, null, null, 1, null, View_QueryBuilderComponent_12)),
        i0.ɵdid(278528, null, 0, i2.NgSwitchCase, [i0.ViewContainerRef, i0.TemplateRef,
            i2.NgSwitch], { ngSwitchCase: [0, 'ngSwitchCase'] }, null), (_l()(), i0.ɵted(null, ['\n                  '])), (_l()(), i0.ɵand(16777216, null, null, 1, null, View_QueryBuilderComponent_14)), i0.ɵdid(278528, null, 0, i2.NgSwitchCase, [i0.ViewContainerRef, i0.TemplateRef, i2.NgSwitch], { ngSwitchCase: [0,
                'ngSwitchCase'] }, null), (_l()(), i0.ɵted(null, ['\n                '])),
        (_l()(), i0.ɵted(null, ['\n            ']))], function (_ck, _v) {
        var _co = _v.component;
        var currVal_7 = _v.parent.parent.context.$implicit.field;
        _ck(_v, 12, 0, currVal_7);
        var currVal_8 = _co.fieldNames;
        _ck(_v, 17, 0, currVal_8);
        var currVal_16 = _v.parent.parent.context.$implicit.operator;
        _ck(_v, 23, 0, currVal_16);
        var currVal_17 = _co.getOperators(_v.parent.parent.context.$implicit.field);
        _ck(_v, 28, 0, currVal_17);
        var currVal_18 = _co.getInputType(_v.parent.parent.context.$implicit.field, _v.parent.parent.context.$implicit.operator);
        _ck(_v, 32, 0, currVal_18);
        var currVal_19 = 'text';
        _ck(_v, 35, 0, currVal_19);
        var currVal_20 = 'date';
        _ck(_v, 38, 0, currVal_20);
        var currVal_21 = 'number';
        _ck(_v, 41, 0, currVal_21);
        var currVal_22 = 'select';
        _ck(_v, 44, 0, currVal_22);
        var currVal_23 = 'multiselect';
        _ck(_v, 47, 0, currVal_23);
        var currVal_24 = 'checkbox';
        _ck(_v, 50, 0, currVal_24);
    }, function (_ck, _v) {
        var currVal_0 = i0.ɵnov(_v, 14).ngClassUntouched;
        var currVal_1 = i0.ɵnov(_v, 14).ngClassTouched;
        var currVal_2 = i0.ɵnov(_v, 14).ngClassPristine;
        var currVal_3 = i0.ɵnov(_v, 14).ngClassDirty;
        var currVal_4 = i0.ɵnov(_v, 14).ngClassValid;
        var currVal_5 = i0.ɵnov(_v, 14).ngClassInvalid;
        var currVal_6 = i0.ɵnov(_v, 14).ngClassPending;
        _ck(_v, 9, 0, currVal_0, currVal_1, currVal_2, currVal_3, currVal_4, currVal_5, currVal_6);
        var currVal_9 = i0.ɵnov(_v, 25).ngClassUntouched;
        var currVal_10 = i0.ɵnov(_v, 25).ngClassTouched;
        var currVal_11 = i0.ɵnov(_v, 25).ngClassPristine;
        var currVal_12 = i0.ɵnov(_v, 25).ngClassDirty;
        var currVal_13 = i0.ɵnov(_v, 25).ngClassValid;
        var currVal_14 = i0.ɵnov(_v, 25).ngClassInvalid;
        var currVal_15 = i0.ɵnov(_v, 25).ngClassPending;
        _ck(_v, 20, 0, currVal_9, currVal_10, currVal_11, currVal_12, currVal_13, currVal_14, currVal_15);
    });
}
function View_QueryBuilderComponent_15(_l) {
    return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, null, null, 1, 'vr-query-builder', [], null, null, null, View_QueryBuilderComponent_0, exports.RenderType_QueryBuilderComponent)), i0.ɵdid(638976, null, 0, i3.QueryBuilderComponent, [], { operatorMap: [0, 'operatorMap'], typeMap: [1, 'typeMap'], parentData: [2,
                'parentData'], data: [3, 'data'], config: [4, 'config'] }, null)], function (_ck, _v) {
        var _co = _v.component;
        var currVal_0 = _co.operatorMap;
        var currVal_1 = _co.typeMap;
        var currVal_2 = _co.data;
        var currVal_3 = _v.parent.parent.context.$implicit;
        var currVal_4 = _co.config;
        _ck(_v, 1, 0, currVal_0, currVal_1, currVal_2, currVal_3, currVal_4);
    }, null);
}
function View_QueryBuilderComponent_16(_l) {
    return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, null, null, 1, 'p', [['class',
                'empty-warning']], null, null, null, null, null)),
        (_l()(), i0.ɵted(null, ['A ruleset cannot be empty. Please add a rule or remove it all together.']))], null, null);
}
function View_QueryBuilderComponent_3(_l) {
    return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, null, null, 15, null, null, null, null, null, null, null)),
        (_l()(), i0.ɵted(null, ['\n          '])), (_l()(), i0.ɵeld(0, null, null, 12, 'li', [], null, null, null, null, null)), i0.ɵdid(278528, null, 0, i2.NgClass, [i0.IterableDiffers, i0.KeyValueDiffers, i0.ElementRef, i0.Renderer], { ngClass: [0,
                'ngClass'] }, null), i0.ɵpod({ 'query-item': 0, 'rule': 1, 'ruleset': 2,
            'invalid-ruleset': 3 }), (_l()(), i0.ɵted(null, ['\n            '])),
        (_l()(), i0.ɵand(16777216, null, null, 1, null, View_QueryBuilderComponent_4)),
        i0.ɵdid(16384, null, 0, i2.NgIf, [i0.ViewContainerRef, i0.TemplateRef], { ngIf: [0,
                'ngIf'] }, null), (_l()(), i0.ɵted(null, ['\n            '])),
        (_l()(), i0.ɵand(16777216, null, null, 1, null, View_QueryBuilderComponent_15)),
        i0.ɵdid(16384, null, 0, i2.NgIf, [i0.ViewContainerRef, i0.TemplateRef], { ngIf: [0,
                'ngIf'] }, null), (_l()(), i0.ɵted(null, ['\n            '])),
        (_l()(), i0.ɵand(16777216, null, null, 1, null, View_QueryBuilderComponent_16)),
        i0.ɵdid(16384, null, 0, i2.NgIf, [i0.ViewContainerRef, i0.TemplateRef], { ngIf: [0,
                'ngIf'] }, null), (_l()(), i0.ɵted(null, ['        \n          '])),
        (_l()(), i0.ɵted(null, ['\n        ']))], function (_ck, _v) {
        var currVal_0 = _ck(_v, 4, 0, true, !_v.context.ngIf.ruleset, _v.context.ngIf.ruleset, _v.context.ngIf.invalid);
        _ck(_v, 3, 0, currVal_0);
        var currVal_1 = !_v.context.ngIf.ruleset;
        _ck(_v, 7, 0, currVal_1);
        var currVal_2 = _v.context.ngIf.ruleset;
        _ck(_v, 10, 0, currVal_2);
        var currVal_3 = _v.context.ngIf.invalid;
        _ck(_v, 13, 0, currVal_3);
    }, null);
}
function View_QueryBuilderComponent_2(_l) {
    return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, null, null, 5, null, null, null, null, null, null, null)),
        (_l()(), i0.ɵted(null, ['\n        '])), (_l()(), i0.ɵand(16777216, null, null, 2, null, View_QueryBuilderComponent_3)), i0.ɵdid(16384, null, 0, i2.NgIf, [i0.ViewContainerRef, i0.TemplateRef], { ngIf: [0, 'ngIf'] }, null), i0.ɵpod({ ruleset: 0, invalid: 1 }), (_l()(), i0.ɵted(null, ['\n      ']))], function (_ck, _v) {
        var _co = _v.component;
        var currVal_0 = _ck(_v, 4, 0, !!_v.context.$implicit.rules, ((!_co.config.allowEmptyRuleset && _v.context.$implicit.rules) && (_v.context.$implicit.rules.length === 0)));
        _ck(_v, 3, 0, currVal_0);
    }, null);
}
function View_QueryBuilderComponent_0(_l) {
    return i0.ɵvid(0, [(_l()(), i0.ɵted(null, ['\n    '])), (_l()(), i0.ɵeld(0, null, null, 14, 'div', [['class', 'switch-field float-right']], null, null, null, null, null)), (_l()(), i0.ɵted(null, ['\n        '])), (_l()(), i0.ɵeld(0, null, null, 3, 'button', [], null, [[null, 'click']], function (_v, en, $event) {
            var ad = true;
            var _co = _v.component;
            if (('click' === en)) {
                var pd_0 = (_co.addRule(_co.data) !== false);
                ad = (pd_0 && ad);
            }
            return ad;
        }, null, null)), (_l()(), i0.ɵeld(0, null, null, 1, 'i', [['class', 'close-icon']], null, null, null, null, null)), (_l()(), i0.ɵted(null, ['➕'])), (_l()(), i0.ɵted(null, [' Rule'])), (_l()(), i0.ɵted(null, ['\n        '])), (_l()(), i0.ɵeld(0, null, null, 3, 'button', [], null, [[null,
                'click']], function (_v, en, $event) {
            var ad = true;
            var _co = _v.component;
            if (('click' === en)) {
                var pd_0 = (_co.addRuleSet(_co.data) !== false);
                ad = (pd_0 && ad);
            }
            return ad;
        }, null, null)), (_l()(), i0.ɵeld(0, null, null, 1, 'i', [['class', 'close-icon']], null, null, null, null, null)), (_l()(), i0.ɵted(null, ['➕'])), (_l()(), i0.ɵted(null, [' Ruleset'])), (_l()(), i0.ɵted(null, ['\n        '])), (_l()(), i0.ɵand(16777216, null, null, 1, null, View_QueryBuilderComponent_1)), i0.ɵdid(16384, null, 0, i2.NgIf, [i0.ViewContainerRef, i0.TemplateRef], { ngIf: [0, 'ngIf'] }, null), (_l()(), i0.ɵted(null, ['\n    '])), (_l()(), i0.ɵted(null, ['\n\n    '])), (_l()(), i0.ɵeld(0, null, null, 23, 'div', [['class',
                'switch-field']], null, null, null, null, null)),
        (_l()(), i0.ɵted(null, ['\n        '])), (_l()(), i0.ɵeld(0, [['andOption',
                1]], null, 6, 'input', [['type', 'radio'], ['value', 'and']], [[2, 'ng-untouched',
                null], [2, 'ng-touched', null], [2, 'ng-pristine', null],
            [2, 'ng-dirty', null], [2, 'ng-valid', null], [2, 'ng-invalid',
                null], [2, 'ng-pending', null]], [[null, 'ngModelChange'],
            [null, 'input'], [null, 'blur'], [null, 'compositionstart'],
            [null, 'compositionend'], [null, 'change']], function (_v, en, $event) {
            var ad = true;
            var _co = _v.component;
            if (('input' === en)) {
                var pd_0 = (i0.ɵnov(_v, 20)._handleInput($event.target.value) !== false);
                ad = (pd_0 && ad);
            }
            if (('blur' === en)) {
                var pd_1 = (i0.ɵnov(_v, 20).onTouched() !== false);
                ad = (pd_1 && ad);
            }
            if (('compositionstart' === en)) {
                var pd_2 = (i0.ɵnov(_v, 20)._compositionStart() !== false);
                ad = (pd_2 && ad);
            }
            if (('compositionend' === en)) {
                var pd_3 = (i0.ɵnov(_v, 20)._compositionEnd($event.target.value) !== false);
                ad = (pd_3 && ad);
            }
            if (('change' === en)) {
                var pd_4 = (i0.ɵnov(_v, 21).onChange() !== false);
                ad = (pd_4 && ad);
            }
            if (('blur' === en)) {
                var pd_5 = (i0.ɵnov(_v, 21).onTouched() !== false);
                ad = (pd_5 && ad);
            }
            if (('ngModelChange' === en)) {
                var pd_6 = ((_co.data.condition = $event) !== false);
                ad = (pd_6 && ad);
            }
            return ad;
        }, null, null)), i0.ɵdid(16384, null, 0, i1.DefaultValueAccessor, [i0.Renderer2, i0.ElementRef, [2, i1.COMPOSITION_BUFFER_MODE]], null, null), i0.ɵdid(212992, null, 0, i1.RadioControlValueAccessor, [i0.Renderer2, i0.ElementRef, i1.ɵi, i0.Injector], { value: [0, 'value'] }, null),
        i0.ɵprd(1024, null, i1.NG_VALUE_ACCESSOR, function (p0_0, p1_0) {
            return [p0_0, p1_0];
        }, [i1.DefaultValueAccessor, i1.RadioControlValueAccessor]), i0.ɵdid(671744, null, 0, i1.NgModel, [[8, null], [8, null], [8, null], [2, i1.NG_VALUE_ACCESSOR]], { model: [0, 'model'] }, { update: 'ngModelChange' }), i0.ɵprd(2048, null, i1.NgControl, null, [i1.NgModel]), i0.ɵdid(16384, null, 0, i1.NgControlStatus, [i1.NgControl], null, null), (_l()(), i0.ɵted(null, ['\n        '])), (_l()(), i0.ɵeld(0, null, null, 1, 'label', [], null, [[null, 'click']], function (_v, en, $event) {
            var ad = true;
            var _co = _v.component;
            if (('click' === en)) {
                var pd_0 = ((_co.data.condition = i0.ɵnov(_v, 19).value) !== false);
                ad = (pd_0 && ad);
            }
            return ad;
        }, null, null)), (_l()(), i0.ɵted(null, ['AND'])),
        (_l()(), i0.ɵted(null, ['\n        '])), (_l()(), i0.ɵeld(0, [['orOption',
                1]], null, 6, 'input', [['type', 'radio'], ['value', 'or']], [[2, 'ng-untouched',
                null], [2, 'ng-touched', null], [2, 'ng-pristine', null],
            [2, 'ng-dirty', null], [2, 'ng-valid', null], [2, 'ng-invalid',
                null], [2, 'ng-pending', null]], [[null, 'ngModelChange'],
            [null, 'input'], [null, 'blur'], [null, 'compositionstart'],
            [null, 'compositionend'], [null, 'change']], function (_v, en, $event) {
            var ad = true;
            var _co = _v.component;
            if (('input' === en)) {
                var pd_0 = (i0.ɵnov(_v, 31)._handleInput($event.target.value) !== false);
                ad = (pd_0 && ad);
            }
            if (('blur' === en)) {
                var pd_1 = (i0.ɵnov(_v, 31).onTouched() !== false);
                ad = (pd_1 && ad);
            }
            if (('compositionstart' === en)) {
                var pd_2 = (i0.ɵnov(_v, 31)._compositionStart() !== false);
                ad = (pd_2 && ad);
            }
            if (('compositionend' === en)) {
                var pd_3 = (i0.ɵnov(_v, 31)._compositionEnd($event.target.value) !== false);
                ad = (pd_3 && ad);
            }
            if (('change' === en)) {
                var pd_4 = (i0.ɵnov(_v, 32).onChange() !== false);
                ad = (pd_4 && ad);
            }
            if (('blur' === en)) {
                var pd_5 = (i0.ɵnov(_v, 32).onTouched() !== false);
                ad = (pd_5 && ad);
            }
            if (('ngModelChange' === en)) {
                var pd_6 = ((_co.data.condition = $event) !== false);
                ad = (pd_6 && ad);
            }
            return ad;
        }, null, null)), i0.ɵdid(16384, null, 0, i1.DefaultValueAccessor, [i0.Renderer2, i0.ElementRef, [2, i1.COMPOSITION_BUFFER_MODE]], null, null), i0.ɵdid(212992, null, 0, i1.RadioControlValueAccessor, [i0.Renderer2, i0.ElementRef, i1.ɵi, i0.Injector], { value: [0, 'value'] }, null),
        i0.ɵprd(1024, null, i1.NG_VALUE_ACCESSOR, function (p0_0, p1_0) {
            return [p0_0, p1_0];
        }, [i1.DefaultValueAccessor, i1.RadioControlValueAccessor]), i0.ɵdid(671744, null, 0, i1.NgModel, [[8, null], [8, null], [8, null], [2, i1.NG_VALUE_ACCESSOR]], { model: [0, 'model'] }, { update: 'ngModelChange' }), i0.ɵprd(2048, null, i1.NgControl, null, [i1.NgModel]), i0.ɵdid(16384, null, 0, i1.NgControlStatus, [i1.NgControl], null, null), (_l()(), i0.ɵted(null, ['\n        '])), (_l()(), i0.ɵeld(0, null, null, 1, 'label', [], null, [[null, 'click']], function (_v, en, $event) {
            var ad = true;
            var _co = _v.component;
            if (('click' === en)) {
                var pd_0 = ((_co.data.condition = i0.ɵnov(_v, 30).value) !== false);
                ad = (pd_0 && ad);
            }
            return ad;
        }, null, null)), (_l()(), i0.ɵted(null, ['OR'])), (_l()(),
            i0.ɵted(null, ['\n    '])), (_l()(), i0.ɵted(null, ['\n\n    '])),
        (_l()(), i0.ɵeld(0, null, null, 4, 'ul', [['class', 'query-tree']], null, null, null, null, null)),
        (_l()(), i0.ɵted(null, ['\n      '])), (_l()(), i0.ɵand(16777216, null, null, 1, null, View_QueryBuilderComponent_2)), i0.ɵdid(802816, null, 0, i2.NgForOf, [i0.ViewContainerRef, i0.TemplateRef, i0.IterableDiffers], { ngForOf: [0, 'ngForOf'] }, null), (_l()(), i0.ɵted(null, ['\n    '])),
        (_l()(), i0.ɵted(null, ['\n  ']))], function (_ck, _v) {
        var _co = _v.component;
        var currVal_0 = !!_co.parentData;
        _ck(_v, 14, 0, currVal_0);
        var currVal_8 = 'and';
        _ck(_v, 21, 0, currVal_8);
        var currVal_9 = _co.data.condition;
        _ck(_v, 23, 0, currVal_9);
        var currVal_17 = 'or';
        _ck(_v, 32, 0, currVal_17);
        var currVal_18 = _co.data.condition;
        _ck(_v, 34, 0, currVal_18);
        var currVal_19 = _co.data.rules;
        _ck(_v, 45, 0, currVal_19);
    }, function (_ck, _v) {
        var currVal_1 = i0.ɵnov(_v, 25).ngClassUntouched;
        var currVal_2 = i0.ɵnov(_v, 25).ngClassTouched;
        var currVal_3 = i0.ɵnov(_v, 25).ngClassPristine;
        var currVal_4 = i0.ɵnov(_v, 25).ngClassDirty;
        var currVal_5 = i0.ɵnov(_v, 25).ngClassValid;
        var currVal_6 = i0.ɵnov(_v, 25).ngClassInvalid;
        var currVal_7 = i0.ɵnov(_v, 25).ngClassPending;
        _ck(_v, 19, 0, currVal_1, currVal_2, currVal_3, currVal_4, currVal_5, currVal_6, currVal_7);
        var currVal_10 = i0.ɵnov(_v, 36).ngClassUntouched;
        var currVal_11 = i0.ɵnov(_v, 36).ngClassTouched;
        var currVal_12 = i0.ɵnov(_v, 36).ngClassPristine;
        var currVal_13 = i0.ɵnov(_v, 36).ngClassDirty;
        var currVal_14 = i0.ɵnov(_v, 36).ngClassValid;
        var currVal_15 = i0.ɵnov(_v, 36).ngClassInvalid;
        var currVal_16 = i0.ɵnov(_v, 36).ngClassPending;
        _ck(_v, 30, 0, currVal_10, currVal_11, currVal_12, currVal_13, currVal_14, currVal_15, currVal_16);
    });
}
exports.View_QueryBuilderComponent_0 = View_QueryBuilderComponent_0;
function View_QueryBuilderComponent_Host_0(_l) {
    return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, null, null, 1, 'vr-query-builder', [], null, null, null, View_QueryBuilderComponent_0, exports.RenderType_QueryBuilderComponent)), i0.ɵdid(638976, null, 0, i3.QueryBuilderComponent, [], null, null)], function (_ck, _v) {
        _ck(_v, 1, 0);
    }, null);
}
exports.View_QueryBuilderComponent_Host_0 = View_QueryBuilderComponent_Host_0;
exports.QueryBuilderComponentNgFactory = i0.ɵccf('vr-query-builder', i3.QueryBuilderComponent, View_QueryBuilderComponent_Host_0, { operatorMap: 'operatorMap',
    typeMap: 'typeMap', parentData: 'parentData', data: 'data', config: 'config' }, {}, []);



/***/ }),

/***/ 88:
/***/ (function(module, exports, __webpack_require__) {

"use strict";

var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
Object.defineProperty(exports, "__esModule", { value: true });
var core_1 = __webpack_require__(20);
var AppComponent = /** @class */ (function () {
    function AppComponent() {
        this.query = {
            condition: 'and',
            rules: [
                { field: 'age', operator: '<=' },
                { field: 'birthday', operator: '>=' },
                {
                    condition: 'or',
                    rules: [
                        { field: 'gender', operator: '=' },
                        { field: 'occupation', operator: 'in' },
                        { field: 'school', operator: 'is null' }
                    ]
                }
            ]
        };
        this.config = {
            fields: {
                'age': { name: 'Age', type: 'number' },
                'gender': {
                    name: 'Gender',
                    type: 'category',
                    options: [
                        { name: 'Male', value: 'm' },
                        { name: 'Female', value: 'f' }
                    ]
                },
                'name': { name: 'Name', type: 'string' },
                'educated': { name: 'College Degree?', type: 'boolean' },
                'birthday': { name: 'Birthday', type: 'date' },
                'school': { name: 'School', type: 'string', nullable: true },
                'occupation': {
                    name: 'Occupation',
                    type: 'string',
                    options: [
                        { name: 'Student', value: 'student' },
                        { name: 'Teacher', value: 'teacher' },
                        { name: 'Unemployed', value: 'unemployed' },
                        { name: 'Scientist', value: 'scientist' }
                    ]
                }
            }
        };
    }
    AppComponent = __decorate([
        core_1.Component({
            selector: 'my-app',
            template: "<vr-query-builder class='margin30' [data]='query' [config]='config'></vr-query-builder>\n  <div class='margin30'>\n      <textarea >{{query | json}}</textarea>\n  </div>",
            styles: ['.margin30 { margin: 30px; }', 'textarea { width: 100%; height: 250px; }']
        })
    ], AppComponent);
    return AppComponent;
}());
exports.AppComponent = AppComponent;


/***/ }),

/***/ 89:
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
Object.defineProperty(__webpack_exports__, "__esModule", { value: true });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "QueryBuilderComponent", function() { return QueryBuilderComponent; });
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__angular_core__ = __webpack_require__(20);

var QueryBuilderComponent = /** @class */ (function () {
    function QueryBuilderComponent() {
        this.defaultEmptyList = [];
        this.typeMap = {
            string: "text",
            number: "number",
            category: "select",
            date: "date",
            boolean: "checkbox"
        };
        this.operatorMap = {
            string: ["=", "!=", "contains", "like"],
            number: ["=", "!=", ">", ">=", "<", "<="],
            category: ["=", "!="],
            date: ["=", "!=", ">", ">=", "<", "<="],
            boolean: ["="]
        };
    }
    QueryBuilderComponent.prototype.ngOnInit = function () {
    };
    QueryBuilderComponent.prototype.ngOnChanges = function (changes) {
        var config = this.config;
        if (typeof config === 'object') {
            this.fieldNames = Object.keys(config.fields);
            this.operatorsCache = {};
        }
        else {
            throw new Error("config must be a valid object");
        }
    };
    QueryBuilderComponent.prototype.getOperators = function (field) {
        if (this.operatorsCache[field]) {
            return this.operatorsCache[field];
        }
        var operators = this.defaultEmptyList;
        if (this.config.getOperators) {
            operators = this.config.getOperators(field);
        }
        var fieldObject = this.config.fields[field];
        var type = fieldObject.type;
        if (field && this.operatorMap[type]) {
            operators = this.operatorMap[type];
        }
        if (fieldObject.options) {
            operators = operators.concat(['in', 'not in']);
        }
        if (fieldObject.nullable) {
            operators = operators.concat(['is null', 'is not null']);
        }
        // Cache reference to array object, so it won't be computed next time and trigger a rerender.
        this.operatorsCache[field] = operators;
        return operators;
    };
    QueryBuilderComponent.prototype.getInputType = function (field, operator) {
        if (this.config.getInputType) {
            return this.config.getInputType(field, operator);
        }
        var type = this.config.fields[field].type;
        switch (operator) {
            case "is null":
            case "is not null":
                return null; // No displayed component
            case "in":
            case "not in":
                return 'multiselect';
            default:
                return this.typeMap[type];
        }
    };
    QueryBuilderComponent.prototype.getOptions = function (field) {
        if (this.config.getOptions) {
            return this.config.getOptions(field);
        }
        return this.config.fields[field].options || this.defaultEmptyList;
    };
    QueryBuilderComponent.prototype.addRule = function (parent) {
        if (this.config.addRule) {
            return this.config.addRule(parent);
        }
        else {
            var field = this.fieldNames[0];
            var fieldObject = this.config.fields[field];
            parent.rules = parent.rules.concat([
                {
                    field: field,
                    operator: this.operatorMap[fieldObject.type][0]
                }
            ]);
        }
    };
    QueryBuilderComponent.prototype.removeRule = function (rule, parent) {
        if (this.config.removeRule) {
            this.config.removeRule(rule, parent);
        }
        else {
            parent.rules = parent.rules.filter(function (r) { return r !== rule; });
        }
    };
    QueryBuilderComponent.prototype.addRuleSet = function (parent) {
        if (this.config.addRuleSet) {
            this.config.addRuleSet(parent);
        }
        else {
            parent.rules = parent.rules.concat([{ condition: "and", rules: [] }]);
        }
    };
    QueryBuilderComponent.prototype.removeRuleSet = function (ruleset, parent) {
        if (this.config.removeRuleSet) {
            this.config.removeRuleSet(ruleset, parent);
        }
        else {
            parent.rules = parent.rules.filter(function (r) { return r !== ruleset; });
        }
    };
    QueryBuilderComponent.prototype.onFieldChange = function (rule) {
        delete rule.value;
        var fieldObject = this.config.fields[rule.field];
        rule.operator = this.operatorMap[fieldObject.type][0];
    };
    QueryBuilderComponent.decorators = [
        { type: __WEBPACK_IMPORTED_MODULE_0__angular_core__["Component"], args: [{
                    selector: 'vr-query-builder',
                    template: "\n    <div class=\"switch-field float-right\">\n        <button (click)=\"addRule(data)\"><i class=\"close-icon\">\u2795</i> Rule</button>\n        <button (click)=\"addRuleSet(data)\"><i class=\"close-icon\">\u2795</i> Ruleset</button>\n        <ng-container *ngIf=\"!!parentData\">\n            <button (click)=\"removeRuleSet(data, parentData)\" class=\"danger\"><i class=\"close-icon\">\u274C</i></button>\n        </ng-container>\n    </div>\n\n    <div class=\"switch-field\">\n        <input type=\"radio\" [(ngModel)]=\"data.condition\" value=\"and\" #andOption/>\n        <label (click)=\"data.condition=andOption.value\">AND</label>\n        <input type=\"radio\" [(ngModel)]=\"data.condition\" value=\"or\" #orOption/>\n        <label (click)=\"data.condition=orOption.value\">OR</label>\n    </div>\n\n    <ul class=\"query-tree\">\n      <ng-container *ngFor=\"let item of data.rules\">\n        <ng-container *ngIf=\"{ruleset: !!item.rules, invalid: !config.allowEmptyRuleset && item.rules && item.rules.length === 0} as local\">\n          <li [ngClass]=\"{'query-item': true, 'rule': !local.ruleset, 'ruleset': local.ruleset, 'invalid-ruleset': local.invalid}\">\n            <ng-container *ngIf=\"!local.ruleset\">\n                <div class=\"switch-field float-right\">\n                  <button class=\"danger\" (click)=\"removeRule(item, data)\"><i class=\"close-icon\">\u274C</i></button>\n                </div>\n\n                <select class=\"form-control\" [(ngModel)]=\"item.field\" (change)=\"onFieldChange(item)\">\n                  <option *ngFor=\"let field of fieldNames\" [ngValue]=\"field\">\n                    {{config.fields[field].name}}\n                  </option>\n                </select>\n                <select class=\"form-control\" [(ngModel)]=\"item.operator\">\n                  <option *ngFor=\"let operator of getOperators(item.field)\" [ngValue]=\"operator\">\n                    {{operator}}\n                  </option>\n                </select>\n                <ng-container [ngSwitch]=\"getInputType(item.field, item.operator)\">\n                  <input class=\"form-control\" [(ngModel)]=\"item.value\" *ngSwitchCase=\"'text'\" type=\"text\">\n                  <input class=\"form-control\" [(ngModel)]=\"item.value\" *ngSwitchCase=\"'date'\" type=\"date\">\n                  <input class=\"form-control\" [(ngModel)]=\"item.value\" *ngSwitchCase=\"'number'\" type=\"number\">\n                  <select class=\"form-control\" [(ngModel)]=\"item.value\" *ngSwitchCase=\"'select'\">\n                    <option *ngFor=\"let opt of getOptions(item.field)\" [ngValue]=\"opt.value\">\n                      {{opt.name}}\n                    </option>\n                  </select>\n                  <ng-container *ngSwitchCase=\"'multiselect'\">\n                    <div style=\"margin-bottom: 8px\"></div>\n                    <select class=\"form-control\" [(ngModel)]=\"item.value\" style=\"min-width: 200px\" multiple>\n                      <option *ngFor=\"let opt of getOptions(item.field)\" [ngValue]=\"opt.value\">\n                        {{opt.name}}\n                      </option>\n                    </select>\n                  </ng-container>\n                  <input class=\"form-control\" [(ngModel)]=\"item.value\" *ngSwitchCase=\"'checkbox'\" type=\"checkbox\">\n                </ng-container>\n            </ng-container>\n            <vr-query-builder *ngIf=\"local.ruleset\" [data]=\"item\" [parentData]=\"data\" [config]=\"config\" [typeMap]=\"typeMap\" [operatorMap]=\"operatorMap\"></vr-query-builder>\n            <p class=\"empty-warning\" *ngIf=\"local.invalid\">A ruleset cannot be empty. Please add a rule or remove it all together.</p>        \n          </li>\n        </ng-container>\n      </ng-container>\n    </ul>\n  ",
                    styles: ["\n    :host{display:block}:host .close-icon{font-style:normal;font-size:12px}:host .switch-field{font-family:\"Lucida Grande\", Tahoma, Verdana, sans-serif;overflow:hidden}:host .float-right{float:right}:host .switch-title{margin-bottom:6px}:host .form-control{display:inline-block;padding:4px 8px;color:#555;background-color:#fff;background-image:none;border:1px solid #ccc;border-radius:4px}:host .switch-field input{position:absolute;clip:rect(0, 0, 0, 0);height:1px;width:1px;border:0;overflow:hidden}:host .switch-field button{margin-left:8px;background-color:white}:host .switch-field label{background-color:#e4e4e4}:host .switch-field label,:host .switch-field button{float:left;min-width:30px;color:rgba(0,0,0,0.6);font-size:14px;font-weight:normal;text-align:center;text-shadow:none;padding:4px 8px;border:1px solid rgba(0,0,0,0.2);-webkit-transition:all 0.1s ease-in-out;-moz-transition:all 0.1s ease-in-out;-ms-transition:all 0.1s ease-in-out;-o-transition:all 0.1s ease-in-out;transition:all 0.1s ease-in-out}:host .switch-field label:hover,:host .switch-field button:hover{cursor:pointer;background-color:#F0F0F0}:host .switch-field label.success,:host .switch-field button.success{color:#75BE47}:host .switch-field label.danger,:host .switch-field button.danger{color:#B3415D}:host .switch-field input:checked+label{border:1px solid #619ed7;background:white;color:#3176b3}:host .invalid-ruleset{border:1px solid rgba(179,65,93,0.5) !important;background:rgba(179,65,93,0.1) !important}:host .empty-warning{color:#8d252e;text-align:center}:host .query-tree{list-style:none;margin:4px 0 2px}:host .query-tree .query-item{position:relative;padding:4px 6px;margin-top:4px;border:1px solid #CCCCCC;-webkit-transition:all 0.1s ease-in-out;-moz-transition:all 0.1s ease-in-out;-ms-transition:all 0.1s ease-in-out;-o-transition:all 0.1s ease-in-out;transition:all 0.1s ease-in-out}:host .query-tree .query-item.ruleset{background:rgba(204,204,204,0.2)}:host .query-tree .query-item.ruleset:hover{border:1px solid rgba(97,158,215,0.5);background:rgba(97,158,215,0.1)}:host .query-tree .query-item.rule{background:white}:host .query-tree .query-item::before{top:-5px;border-width:0 0 2px 2px}:host .query-tree .query-item::after{border-width:0 0 0 2px;top:50%}:host .query-tree .query-item::before,:host .query-tree .query-item::after{content:'';left:-12px;border-color:#CCC;border-style:solid;width:9px;height:calc(50% + 6px);position:absolute}:host .query-tree .query-item:last-child::after{content:none}\n  "]
                },] },
    ];
    /** @nocollapse */
    QueryBuilderComponent.ctorParameters = function () { return []; };
    QueryBuilderComponent.propDecorators = {
        'operatorMap': [{ type: __WEBPACK_IMPORTED_MODULE_0__angular_core__["Input"] },],
        'typeMap': [{ type: __WEBPACK_IMPORTED_MODULE_0__angular_core__["Input"] },],
        'parentData': [{ type: __WEBPACK_IMPORTED_MODULE_0__angular_core__["Input"] },],
        'data': [{ type: __WEBPACK_IMPORTED_MODULE_0__angular_core__["Input"] },],
        'config': [{ type: __WEBPACK_IMPORTED_MODULE_0__angular_core__["Input"] },],
    };
    return QueryBuilderComponent;
}());

//# sourceMappingURL=query-builder.component.js.map

/***/ })

},[303]);
//# sourceMappingURL=main.js.map